-- FinApp Database Initialization Script
-- Database: finapp
-- MySQL 8.0

-- Create database if not exists
CREATE DATABASE IF NOT EXISTS `finapp` 
DEFAULT CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE `finapp`;

-- ============================================
-- Table: Users
-- ============================================
CREATE TABLE IF NOT EXISTS `Users` (
    `Id` INT AUTO_INCREMENT PRIMARY KEY,
    `Username` VARCHAR(50) NOT NULL UNIQUE,
    `PasswordHash` VARCHAR(255) NOT NULL,
    `Email` VARCHAR(100) NOT NULL,
    `FullName` VARCHAR(100) NOT NULL,
    `Role` VARCHAR(20) NOT NULL DEFAULT 'User',
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_username` (`Username`),
    INDEX `idx_email` (`Email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Table: STPB (Surat Tanda Pertanggungjawaban Belanja)
-- ============================================
CREATE TABLE IF NOT EXISTS `STPB` (
    `Id` INT AUTO_INCREMENT PRIMARY KEY,
    `NomorSTPB` VARCHAR(50) NOT NULL UNIQUE,
    `Tanggal` DATE NOT NULL,
    `Deskripsi` TEXT,
    `NilaiTotal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    `Status` VARCHAR(20) NOT NULL DEFAULT 'Draft',
    `CreatedBy` INT NOT NULL,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`CreatedBy`) REFERENCES `Users`(`Id`) ON DELETE CASCADE,
    INDEX `idx_nomor` (`NomorSTPB`),
    INDEX `idx_tanggal` (`Tanggal`),
    INDEX `idx_status` (`Status`),
    INDEX `idx_createdby` (`CreatedBy`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- Seed Data: Default Admin User
-- ============================================
-- Password: Admin123! (BCrypt hashed)
-- Note: Hash will be generated by application on first run
INSERT INTO `Users` (`Username`, `PasswordHash`, `Email`, `FullName`, `Role`, `IsActive`) 
VALUES (
    'admin',
    '$2a$11$kZXqVvCmJ6QqVEv0h5YqJOXxGZqI3YYbJxJZqQqZ1qZ1qZ1qZ1qZ1q',
    'admin@finapp.com',
    'Administrator',
    'Admin',
    1
) ON DUPLICATE KEY UPDATE `Username`='admin';

-- ============================================
-- Sample STPB Data (Optional for testing)
-- ============================================
-- INSERT INTO `STPB` (`NomorSTPB`, `Tanggal`, `Deskripsi`, `NilaiTotal`, `Status`, `CreatedBy`)
-- VALUES 
-- ('STPB/2026/001', '2026-01-15', 'Pembelian Alat Tulis Kantor', 5000000.00, 'Draft', 1),
-- ('STPB/2026/002', '2026-01-16', 'Pembelian Komputer', 15000000.00, 'Submitted', 1),
-- ('STPB/2026/003', '2026-01-17', 'Biaya Perjalanan Dinas', 3500000.00, 'Approved', 1);

-- ============================================
-- Verify Tables
-- ============================================
SHOW TABLES;

SELECT 'Database initialization completed successfully!' AS Result;
