// <auto-generated />
using System;
using FinApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203061301_AddTanggalTransaksiToStpbDetail")]
    partial class AddTanggalTransaksiToStpbDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FinApp.Domain.Entities.Akun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SubkomponenId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Nama");

                    b.HasIndex("SubkomponenId");

                    b.ToTable("Akuns", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.AnggaranMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bkpk")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("HargaSat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HasilReviuKonsolidasiBaru")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KdAkun")
                        .HasColumnType("longtext");

                    b.Property<string>("KdBeban")
                        .HasColumnType("longtext");

                    b.Property<string>("KdDekon")
                        .HasColumnType("longtext");

                    b.Property<string>("KdDept")
                        .HasColumnType("longtext");

                    b.Property<string>("KdFungsi")
                        .HasColumnType("longtext");

                    b.Property<string>("KdGiat")
                        .HasColumnType("longtext");

                    b.Property<string>("KdKmpnen")
                        .HasColumnType("longtext");

                    b.Property<string>("KdOutput")
                        .HasColumnType("longtext");

                    b.Property<string>("KdProgram")
                        .HasColumnType("longtext");

                    b.Property<string>("KdSDana")
                        .HasColumnType("longtext");

                    b.Property<string>("KdSFung")
                        .HasColumnType("longtext");

                    b.Property<string>("KdSOutput")
                        .HasColumnType("longtext");

                    b.Property<string>("KdSatker")
                        .HasColumnType("longtext");

                    b.Property<string>("KdSkmpnen")
                        .HasColumnType("longtext");

                    b.Property<string>("KdUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("KomponenPendukung")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Netto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NmAkun")
                        .HasColumnType("longtext");

                    b.Property<string>("NmDekon")
                        .HasColumnType("longtext");

                    b.Property<string>("NmDept")
                        .HasColumnType("longtext");

                    b.Property<string>("NmFungsi")
                        .HasColumnType("longtext");

                    b.Property<string>("NmGiat")
                        .HasColumnType("longtext");

                    b.Property<string>("NmItem")
                        .HasColumnType("longtext");

                    b.Property<string>("NmKmpnen")
                        .HasColumnType("longtext");

                    b.Property<string>("NmOutput")
                        .HasColumnType("longtext");

                    b.Property<string>("NmProgram")
                        .HasColumnType("longtext");

                    b.Property<string>("NmSDana")
                        .HasColumnType("longtext");

                    b.Property<string>("NmSFung")
                        .HasColumnType("longtext");

                    b.Property<string>("NmSOutput")
                        .HasColumnType("longtext");

                    b.Property<string>("NmSatker")
                        .HasColumnType("longtext");

                    b.Property<string>("NmSkmpnen")
                        .HasColumnType("longtext");

                    b.Property<string>("NmUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("NoItem")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Pagu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Register")
                        .HasColumnType("longtext");

                    b.Property<int>("Revisi")
                        .HasColumnType("int");

                    b.Property<string>("SatKeg")
                        .HasColumnType("longtext");

                    b.Property<int>("TahunAnggaran")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VolKeg")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AnggaranMasters", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AkunId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("HargaSatuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AkunId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Nama");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Kegiatan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Nama");

                    b.HasIndex("ProgramId");

                    b.ToTable("Kegiatans", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Komponen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SuboutputId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Nama");

                    b.HasIndex("SuboutputId");

                    b.ToTable("Komponens", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Output", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<Guid>("KegiatanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("KegiatanId");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Nama");

                    b.ToTable("Outputs", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.PpkBendahara", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("Jabatan")
                        .HasColumnType("int");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("NIP")
                        .IsUnique();

                    b.HasIndex("Nama");

                    b.ToTable("PpkBendahara", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Nama");

                    b.ToTable("Programs", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator dengan akses penuh",
                            IsAdmin = true,
                            Name = "Admin",
                            UpdatedAt = new DateTime(2026, 2, 3, 6, 12, 59, 396, DateTimeKind.Utc).AddTicks(4552)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "User biasa dengan akses terbatas",
                            IsAdmin = false,
                            Name = "User",
                            UpdatedAt = new DateTime(2026, 2, 3, 6, 12, 59, 396, DateTimeKind.Utc).AddTicks(4570)
                        });
                });

            modelBuilder.Entity("FinApp.Domain.Entities.RoleSuboutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KodeSuboutput")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "KodeSuboutput")
                        .IsUnique();

                    b.ToTable("RoleSuboutputs", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.SequenceNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "Year")
                        .IsUnique();

                    b.ToTable("SequenceNumbers", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Stpb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text");

                    b.Property<string>("NomorSTPB")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("PpkBendaharaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tahun")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalSTPB")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalNilai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NomorSTPB")
                        .IsUnique();

                    b.HasIndex("PpkBendaharaId");

                    b.HasIndex("Status");

                    b.HasIndex("Tahun");

                    b.HasIndex("TanggalSTPB");

                    b.ToTable("STPB", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.StpbDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("HargaSatuan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("JumlahHarga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text");

                    b.Property<string>("KodeAkun")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KodeKegiatan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KodeKomponen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KodeOutput")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KodeProgram")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KodeSubkomponen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KodeSuboutput")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NamaAkun")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NamaItem")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NamaKegiatan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NamaKomponen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NamaOutput")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NamaProgram")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NamaSubkomponen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NamaSuboutput")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("NilaiBersih")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NoItem")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("PPH21")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PPH22")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PPH23")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PPN")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Penerima")
                        .HasColumnType("longtext");

                    b.Property<int>("Revisi")
                        .HasColumnType("int");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("StpbId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tahun")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalTransaksi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("KodeSuboutput");

                    b.HasIndex("StpbId");

                    b.ToTable("StpbDetails", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Subkomponen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("KomponenId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("KomponenId");

                    b.HasIndex("Nama");

                    b.ToTable("Subkomponens", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Suboutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("OutputId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Nama");

                    b.HasIndex("OutputId");

                    b.ToTable("Suboutputs", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("PpkBendaharaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("PpkBendaharaId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@finapp.com",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$VyFHd84rlCboUP.RPn25qeR7gw9i39bjj65fARIUvG6JkSjv.E2mW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000010"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Akun", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.Subkomponen", "Subkomponen")
                        .WithMany("Akuns")
                        .HasForeignKey("SubkomponenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subkomponen");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Item", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.Akun", "Akun")
                        .WithMany("Items")
                        .HasForeignKey("AkunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Akun");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Kegiatan", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.Program", "Program")
                        .WithMany("Kegiatans")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Komponen", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.Suboutput", "Suboutput")
                        .WithMany("Komponens")
                        .HasForeignKey("SuboutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suboutput");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Output", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.Kegiatan", "Kegiatan")
                        .WithMany("Outputs")
                        .HasForeignKey("KegiatanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kegiatan");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.RoleSuboutput", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.Role", "Role")
                        .WithMany("RoleSuboutputs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Stpb", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.User", "Creator")
                        .WithMany("StpbList")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinApp.Domain.Entities.PpkBendahara", "PpkBendahara")
                        .WithMany("Stpbs")
                        .HasForeignKey("PpkBendaharaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("PpkBendahara");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.StpbDetail", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinApp.Domain.Entities.Stpb", "Stpb")
                        .WithMany("StpbDetails")
                        .HasForeignKey("StpbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Stpb");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Subkomponen", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.Komponen", "Komponen")
                        .WithMany("Subkomponens")
                        .HasForeignKey("KomponenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Komponen");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Suboutput", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.Output", "Output")
                        .WithMany("Suboutputs")
                        .HasForeignKey("OutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Output");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.User", b =>
                {
                    b.HasOne("FinApp.Domain.Entities.PpkBendahara", "PpkBendahara")
                        .WithMany()
                        .HasForeignKey("PpkBendaharaId");

                    b.HasOne("FinApp.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PpkBendahara");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Akun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Kegiatan", b =>
                {
                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Komponen", b =>
                {
                    b.Navigation("Subkomponens");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Output", b =>
                {
                    b.Navigation("Suboutputs");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.PpkBendahara", b =>
                {
                    b.Navigation("Stpbs");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Program", b =>
                {
                    b.Navigation("Kegiatans");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleSuboutputs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Stpb", b =>
                {
                    b.Navigation("StpbDetails");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Subkomponen", b =>
                {
                    b.Navigation("Akuns");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.Suboutput", b =>
                {
                    b.Navigation("Komponens");
                });

            modelBuilder.Entity("FinApp.Domain.Entities.User", b =>
                {
                    b.Navigation("StpbList");
                });
#pragma warning restore 612, 618
        }
    }
}
